clone:
  depth: 10
cache:
  mount:
    - node_modules
    - .git
environment:
  - CLICOLOR_FORCE=1
  - FORCE_COLOR=1
  - TERM=xterm-256color

build:
  test:
    image: node:6
    commands:
      - npm install --quiet --color --unsafe-perm
      - npm test --quiet --color
  lint:
    image: node:6
    commands:
      - npm install --quiet --color --unsafe-perm
      - npm run lint --quiet --color
