clone:
  depth: 10
cache:
  mount:
    - node_modules
    - .git
build:
  image: node:6
  commands:
    - npm install --quiet --colors
    - npm run ci --quiet --colors
publish:
  sftp:
    host: 127.0.0.1
    port: 22
    username: $$COVERAGE_USER_NAME
    password: $$COVERAGE_USER_PASSWORD
    destination_path: /var/www/coverage/$$BRANCH
    files:
      - lint.xml
      - coverage/*